" :PlugInstall
call plug#begin()
Plug 'dense-analysis/ale'
Plug 'vim-airline/vim-airline'
call plug#end()

colorscheme e1c411f

let g:ale_fixers = {'cpp': ['clang-format',]}
let g:ale_fix_on_save = 1

set incsearch
set hlsearch
set ignorecase
noremap n nzz
noremap N Nzz

nnoremap <silent> <Esc><Esc> :let @/ = ""<CR>

set wildmenu

set t_Co=256

set tabstop=2
set shiftwidth=2
set expandtab

nnoremap Y y$

set scrolloff=3

set number

set noerrorbells
set visualbell

nnoremap <C-s> :w<CR>
inoremap <C-s> <Esc>:w<CR>

nnoremap <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
      \ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
      \ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
