name: PR pipeline

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: pull_request_pipeline
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
      shell: zsh {0}
    - name: unittests
      run: make unittests
      shell: zsh {0}
    - name: perftests
      run: make perftests
      shell: zsh {0}
