name: PR pipeline

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: PR pipeline
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make all
      run: make
    - name: Run unit tests
      run: make unittests
    - name: Run performance tests
      run: make perftests
